# Generated by Django 5.2.9 on 2025-12-03 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='renderedphoto',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qrcodes/'),
        ),
        migrations.AddField(
            model_name='session',
            name='download_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
