# Generated by Django 5.2.9 on 2025-12-04 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_renderedphoto_qr_code_session_download_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='selected_frame',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='core.frame'),
        ),
        migrations.CreateModel(
            name='PhotoSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_index', models.IntegerField()),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('frame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.frame')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='core.photo')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='core.session')),
            ],
            options={
                'ordering': ['order', 'slot_index'],
                'unique_together': {('session', 'frame', 'slot_index')},
            },
        ),
    ]
